### ISSUE TITLE
Support for Central Package Management

### ISSUE THREAD

**Issue by dagochen** [tomchavakis/nuget-license#127]
In April Microsoft introduced [Central Package Management](https://devblogs.microsoft.com/nuget/introducing-central-package-management/). The current version (2.4) does not produce any result when using CPM. 

Are there any plans to support CPM and if so, when?

We also tried the 3.0.0-alpha5 and ran 4into an exception:
`dotnet-project-licenses -i .\src\<ProjectName>\<ProjectFile>.csproj`

```
System.ArgumentException: Value cannot be null or an empty string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Versioning.NuGetVersion..ctor(String version)
   at NuGetUtility.Wrapper.NuGetWrapper.Versioning.WrappedNuGetVersion..ctor(String version) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Wrapper/NuGetWrapper/Versioning/WrappedNuGetVersion.cs:line 16
   at NuGetUtility.Wrapper.MsBuildWrapper.MsBuildAbstraction.<>c.<GetPackageReferencesFromProjectForFramework>b__2_1(ITaskItem p) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Wrapper/MsBuildWrapper/MsBuildAbstraction.cs:line 33
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.IsDirectlyReferenced(ILockFileLibrary library, IEnumerable`1 directlyReferencedPackages) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/ReferencedPackagesReader/ReferencedPackageReader.cs:line 88
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.<>c__DisplayClass8_0.<GetReferencedLibrariesForTarget>b__1(ILockFileLibrary l) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/ReferencedPackagesReader/ReferencedPackageReader.cs:line 74
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGetUtility.Extensions.HashSetExtension.AddRange[T](HashSet`1 source, IEnumerable`1 items) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Extensions/HashSetExtension.cs:line 15
   at NuGetUtility.ReferencedPackagesReader.ReferencedPackageReader.GetInstalledPackagesFromAssetsFile(Boolean includeTransitive, IProject project) in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/ReferencedPackagesReader/ReferencedPackageReader.cs:line 52
   at NuGetUtility.Program.OnExecuteAsync() in /home/runner/work/nuget-license/nuget-license/src/NuGetUtility/Program.cs:line 0
```

**Comment by sensslen** [comment]
Digging deeper - it seems support for this feature is a matter of updating the referenced NuGet packages in the 3.0.0 branch… would you mind testing?

**Comment by jdrst** [comment]
With updated packages in `NugetUtility.csproj` the error persists.

```xml
    <ItemGroup>
        <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.0.1" />
        <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" Version="17.3.1" />
        <PackageReference Include="Microsoft.Build.Locator" Version="1.5.5" />
        <PackageReference Include="NuGet.Commands" Version="6.3.0" />
        <PackageReference Include="NuGet.Packaging" Version="6.3.0" />
    </ItemGroup>
```

**Comment by sensslen** [comment]
In that case a minimal example for the error would be very nice. I'll check the error when I get time. Alternatively you coud also try and find the issue yourself. Pull Requests are welcome....

**Comment by jdrst** [comment]
here's a minimal example that reproduces the error:
[CentralPackageManagementMinimal.zip](https://github.com/tomchavakis/nuget-license/files/9503365/CentralPackageManagementMinimal.zip)

**Comment by jdrst** [comment]
i will try for a fix today but can't make any promises :D

**Comment by sensslen** [comment]
That's more than enough - I can neither make any promises other than I will not be able to look into it today....

**Comment by jdrst** [comment]
found the problem. 

after running it, i have to say though that in the current state of v3 our usecase for this package isn't represented anymore.
we were using dotnet-project-licenses to generate a text file (with links to the projects) we can then deliver alongside our releases. 

- current output misses links to the projects and the documentation gives no hint on how to include these.
- package-ignoring got messier imho, i personally prefer it inline when calling the tool instead of having to put a json file somewhere.
- while i can pipe results into a file, i personally also prefer having an explicit output parameter for that
- while i can now group projects via json, just throwing my solution in is imho easier

are these features that just didn't make the refactoring cut yet or are you not planning on including them?

**Comment by sensslen** [comment]
The new version is in alpha state on purpose. Many features of the original are still missing. The goal here was to move to a more sustainable base (using microsofts implementation for retreiving nuget information). Another goal was to evaluate which features of the original were actively used to include them bit by bit instead of just moving everything over. Feel free to create issues for the missing features so that they can be tracked seperately.

**Comment by jdrst** [comment]
would you then be willing to accept prs for those or do you want to wait and see if there's interest?

**Comment by sensslen** [comment]
Of course PR‘s are welcome - however keep in mind to keep the architecture as clean as possible.

**Comment by sensslen** [comment]
@jdrst I just opened a PR implementing one of your requests: #144
