### ISSUE TITLE
TaskCanceledException while running tool in Azure Pipeline

### ISSUE THREAD

**Issue by actuallyrob** [tomchavakis/nuget-license#64]
I have implemented this tool in my Azure Pipeline to list all dependencies and obtain all licenses in order to list them in my frontend. 

I run into an exception however when executing this tool in a build Agent:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NugetUtility.Methods.ExportLicenseTexts(List`1 infos) in /home/runner/work/nuget-license/nuget-license/src/Methods.cs:line 748
   at NugetUtility.Program.Execute(PackageOptions options) in /home/runner/work/nuget-license/nuget-license/src/Program.cs:line 40
```

I execute this tool as following:
`dotnet-project-licenses -i {path to solution} -u -o {output path}/licenses.json -j --export-license-texts`

The solution that I use this tool for consists of multiple .NET Framework 4.x projects. This tool works fine on said solution when I run it on my local machine.

This error doesn't show up every time that I execute my pipeline, but I cannot rely on it working 50% of the time.

Any idea what I'm doing wrong?

**Comment by actuallyrob** [comment]
I have found the issue. I had configured my Build Agent to stop on first error, causing the execution of the tool to be interrupted when a license file could not be found.

**Comment by tomchavakis** [comment]
Hi @actuallyrob,

It's great that this tool is running in your Azure CI/CD. 
I would like to ask you if you believe that a docker would be better for your pipeline?
